export const FETCH_EFFECTIVE_SYMBOLS = 'FETCH_EFFECTIVE_SYMBOLS'
export const FETCH_EFFECTIVE_SYMBOLS_LOADING = 'FETCH_EFFECTIVE_SYMBOLS_LOADING'
export const FETCH_EFFECTIVE_SYMBOLS_ERROR = 'FETCH_EFFECTIVE_SYMBOLS_ERROR'
export const FETCH_EFFECTIVE_SYMBOLS_GET = 'FETCH_EFFECTIVE_SYMBOLS_GET'