export const FETCH_DATA_PREORDER = 'DATA_PREORDER'
export const FETCH_DATA_ORDER = 'DATA_ORDER'
export const FETCH_CURRNET_ORDERS = 'CURRENT_ORDERS'

export const CHANGE_CURRENT_ORDERS = 'CHANGE_CURRENT_ORDERS'