export const FETCH_PURCHASING_POWER = 'FETCH_PURCHASING_POWER';
export const SET_PURCHASING_POWER = 'SET_PURCHASING_POWER';
export const SET_PURCHASING_POWER_LOADING = 'SET_PURCHASING_POWER_LOADING';
export const PURCHASING_POWER_YOU_NOT_LOGED_IN = 'PURCHASING_POWER_YOU_NOT_LOGED_IN';